# Generated by Django 5.0.1 on 2024-02-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.IntegerField(choices=[('draft', 'Draft'), ('public', 'Published')], default='draft'),
        ),
    ]
